const proposalsData = [
  {
    id: '001.21',
    work: 'Barker Group',
    customer: 'Brown and Glass',
    employee: 'Julia Huff',
    seller: 'Benjamin Patrick',
    priority: 'Urgente',
    category: 'orçamento',
    description: 'Throw Congress have experience color appear. Computer attention picture national project station TV change. Charge game exactly according spend interview so. Force today enough book lot.',
    value: 1153787,
    status: 'concluido',
    created: '01/01/2021',
    date_conclusion: '01/01/2021'
  },
  {
    id: '002.21',
    work: 'Chan, Larsen and Lee',
    customer: 'Carter LLC',
    employee: 'Wendy Alvarez',
    seller: 'Caroline Hernandez',
    priority: 'Normal',
    category: 'orçamento',
    description: 'Movie choose artist sell site program which. Member reality kitchen. Purpose become remember rest relationship trial today.',
    value: 307864,
    status: 'em elaboração',
    created: '02/01/2021',
    date_conclusion: '02/01/2021'
  },
  {
    id: '003.21',
    work: 'Chen and Sons',
    customer: 'Chan-Jones',
    employee: 'Taylor Watkins',
    seller: 'Christopher Fisher',
    priority: 'Alta',
    category: 'extra',
    description: 'Report idea plan. Many class keep story Congress choice anything summer. Reach line story actually because wear one.',
    value: 1814578,
    status: 'pendente',
    created: '03/01/2021',
    date_conclusion: '03/01/2021'
  },
  {
    id: '004.21',
    work: 'Collins, Stuart and Hodges',
    customer: 'Coleman-Schneider',
    employee: 'Debra Jenkins',
    seller: 'Cody Brown',
    priority: 'Baixa',
    category: 'consulta',
    description: 'May rise college condition PM. Hair will so summer any region. Could might structure role manage particularly. Maybe road large leader. Hear need culture too between sport. If young heart left last.',
    value: 724816,
    status: 'não iniciado',
    created: '04/01/2021',
    date_conclusion: '04/01/2021'
  },
  {
    id: '005.21',
    work: 'Davis and Sons',
    customer: 'Gutierrez-Joseph',
    employee: 'John Dixon',
    seller: 'Dakota Reed',
    priority: 'Normal',
    category: 'consulta',
    description: 'Allow develop into civil education lay. Health hundred score ahead anyone sell catch.',
    value: 1350611,
    status: 'em elaboração',
    created: '05/01/2021',
    date_conclusion: '05/01/2021'
  },
  {
    id: '006.21',
    work: 'Douglas Building',
    customer: 'Holland Inc',
    employee: 'Anthony Strong',
    seller: 'Jacob King',
    priority: 'Alta',
    category: 'orçamento',
    description: 'Year player southern show skin. Than approach generation green improve. Everything lay give magazine thousand. Down strategy inside range. Sound case network scientist bed sort past.',
    value: 675229,
    status: 'não iniciado',
    created: '06/01/2021',
    date_conclusion: '06/01/2021'
  },
  {
    id: '007.21',
    work: 'Ellis, Hunt and Dean',
    customer: 'Holloway and Flynn',
    employee: 'Kaitlyn Powell',
    seller: 'Joel Allen',
    priority: 'Normal',
    category: 'global',
    description: 'Involve week suffer nearly. Again she list itself during chair require. Again result model wide. Media really their. Rule office word box parent loss.',
    value: 1611444,
    status: 'em elaboração',
    created: '07/01/2021',
    date_conclusion: '07/01/2021'
  },
  {
    id: '008.21',
    work: 'Franco-Roberts',
    customer: 'Howard Fisher',
    employee: 'Brandy Roman',
    seller: 'John Jacobson II',
    priority: 'Urgente',
    category: 'particular',
    description: 'Man explain stage floor. Impact quite purpose include daughter population. Bad thing action together never. Drop sort organization. Pattern reality him.',
    value: 1578496,
    status: 'cancelado',
    created: '08/01/2021',
    date_conclusion: '08/01/2021'
  },
  {
    id: '009.21',
    work: 'Gonzalez-Smith',
    customer: 'Lee PLC',
    employee: 'John Davis',
    seller: 'John Melendez',
    priority: 'Normal',
    category: 'cotação',
    description: 'Cover various ago consumer. Meeting successful recent certainly citizen. Stock attention hospital race animal score fill. Than type school really woman continue season. Rest now old court.',
    value: 151748,
    status: 'não iniciado',
    created: '09/01/2021',
    date_conclusion: '09/01/2021'
  },
  {
    id: '010.21',
    work: 'Long, Johnston and Vargas',
    customer: 'Lopez and Johnson',
    employee: 'Michelle Franklin',
    seller: 'Keith Schultz',
    priority: 'Alta',
    category: 'cotação',
    description: 'Professional although fish smile behavior. End short public myself speech. Than door strategy sport parent smile.',
    value: 1864922,
    status: 'pendente',
    created: '10/01/2021',
    date_conclusion: '10/01/2021'
  },
  {
    id: '011.21',
    work: 'Martinez Building',
    customer: 'Martinez Group',
    employee: 'Melinda Hernandez',
    seller: 'Kenneth Gallegos',
    priority: 'Baixa',
    category: 'concorrência',
    description: 'American particularly can party herself available. Carry hundred research visit suddenly condition road begin. Bag them increase similar other fly indicate. Attention lawyer bar.',
    value: 1325334,
    status: 'não iniciado',
    created: '11/01/2021',
    date_conclusion: '11/01/2021'
  },
  {
    id: '012.21',
    work: 'Nicholson Ltd',
    customer: 'Mcbride-Owen',
    employee: 'Christopher Ayala MD',
    seller: 'Krystal Ramirez',
    priority: 'Normal',
    category: 'concorrência',
    description: 'Culture discussion wind interest. Pattern bill main must. Painting community bag remain. Trial get when certainly. Environment improve change project which cell. Media continue history woman.',
    value: 144202,
    status: 'concluido',
    created: '12/01/2021',
    date_conclusion: '12/01/2021'
  },
  {
    id: '013.21',
    work: 'Ortiz-Foster',
    customer: 'One Stop Building',
    employee: 'Michelle Blackwell',
    seller: 'Mark Dudley',
    priority: 'Normal',
    category: 'global',
    description: 'Agent father authority between. Doctor far red whose. Early turn data bad protect mean most. Why according month hold number.',
    value: 902692,
    status: 'não iniciado',
    created: '13/01/2021',
    date_conclusion: '13/01/2021'
  },
  {
    id: '014.21',
    work: 'Prince-Callahan',
    customer: 'Reyes-Pope',
    employee: 'Lawrence Shaffer',
    seller: 'Michael Lang',
    priority: 'Alta',
    category: 'orçamento',
    description: 'Available citizen expect employee same structure skin. Last stand free produce type month major. Ability mean law audience. Grow result meet field themselves involve.',
    value: 1908839,
    status: 'pendente',
    created: '14/01/2021',
    date_conclusion: '14/01/2021'
  },
  {
    id: '015.21',
    work: 'Riley Ltd',
    customer: 'Simple Trade',
    employee: 'Jeffery Price',
    seller: 'Nathaniel Simpson',
    priority: 'Alta',
    category: 'consulta',
    description: 'Catch environment that pay race. Ago half no someone. Level picture model language film. Attention science involve police tonight idea appear.',
    value: 1266396,
    status: 'aprovado',
    created: '15/01/2021',
    date_conclusion: '15/01/2021'
  },
  {
    id: '016.21',
    work: 'Smith Group',
    customer: 'Sparks and Griffith',
    employee: 'Natalie Clark',
    seller: 'Ryan Wells',
    priority: 'Normal',
    category: 'cotação',
    description: 'Green their yeah fall whom sea boy. Run hour personal top. Billion crime audience according hand.',
    value: 1568726,
    status: 'concluido',
    created: '16/01/2021',
    date_conclusion: '16/01/2021'
  },
  {
    id: '017.21',
    work: 'Smith, Wilkinson and Brandt',
    customer: 'Stevens and Quinn',
    employee: 'Katherine Kaufman',
    seller: 'Sean Mercer',
    priority: 'Normal',
    category: 'particular',
    description: 'Statement relate such rather market church young future. Now choose certain game say each. Eat care must member language think.',
    value: 1833264,
    status: 'não iniciado',
    created: '17/01/2021',
    date_conclusion: '17/01/2021'
  },
  {
    id: '018.21',
    work: 'Smith-Brown',
    customer: 'Stone Fisher',
    employee: 'Kara Nguyen',
    seller: 'Sean Reed',
    priority: 'Baixa',
    category: 'particular',
    description: 'Control its network rich. Political about subject will simply throw task member. Theory behavior option realize. Six yet organization girl set door current. Ten forget drop science two.',
    value: 1231923,
    status: 'pendente',
    created: '18/01/2021',
    date_conclusion: '18/01/2021'
  },
  {
    id: '019.21',
    work: 'White, Garcia and Duncan',
    customer: 'Stone Ltda',
    employee: 'Lisa Flowers',
    seller: 'Taylor Taylor',
    priority: 'Urgente',
    category: 'concorrência',
    description: 'Yeah bill few outside beat. At same find. Note eight here action lead left bag. Large structure worry enter. White poor woman professor person recently husband.',
    value: 726686,
    status: 'não iniciado',
    created: '19/01/2021',
    date_conclusion: '19/01/2021'
  },
  {
    id: '020.21',
    work: 'Wood House',
    customer: 'Thompson SA',
    employee: 'Zachary Robinson',
    seller: 'Victoria Haas',
    priority: 'Alta',
    category: 'cotação',
    description: 'Wait think computer up tell the. Democrat game hour which community contain interest.',
    value: 811556,
    status: 'aprovado',
    created: '20/01/2021',
    date_conclusion: '20/01/2021'
  },
]

export default proposalsData
