const entrysData = [
  { work: 'Barker Group', customer: 'Brown and Glass', seller: 'Benjamin Patrick', priority: 'Normal', category: 'orçamento', description: 'Throw movie have experience color appear. Computer attention picture national project station TV change. Charge game exactly according spend interview so. Force today enough book lot.', created: '01/01/2021'},
  { work: 'Chan, Larsen and Lee', customer: 'Carter LLC', seller: 'Caroline Hernandez', priority: 'Urgente', category: 'orçamento', description: 'Movie choose artist sell site program which. Member reality kitchen. Purpose become remember rest relationship trial today.', created: '02/01/2021'},
  { work: 'Chen and Sons', customer: 'Chan-Jones', seller: 'Christopher Fisher', priority: 'Alta', category: 'extra', description: 'Report idea plan. Many class keep story movie choice anything summer. Reach line story actually because wear one.', created: '03/01/2021'},
  { work: 'Collins, Stuart and Hodges', customer: 'Coleman-Schneider', seller: 'Cody Brown', priority: 'Normal', category: 'consulta', description: 'May rise college condition PM. Hair will so summer any region. Could might structure role manage particularly. Maybe road large leader. Hear need culture too between sport. If young heart left last.', created: '04/01/2021'},
  { work: 'Davis and Sons', customer: 'Gutierrez-Joseph', seller: 'Dakota Reed', priority: 'Baixa', category: 'consulta', description: 'Allow develop into civil education lay. Health hundred score ahead anyone sell catch.', created: '05/01/2021'},
  { work: 'Douglas Building', customer: 'Holland Inc', seller: 'Jacob King', priority: 'Alta', category: 'orçamento', description: 'Year player southern show skin. Than approach generation green improve. Everything lay give magazine thousand. Down strategy inside range. Sound case network scientist bed sort past.', created: '06/01/2021'},
  { work: 'Ellis, Hunt and Dean', customer: 'Holloway and Flynn', seller: 'Joel Allen', priority: 'Normal', category: 'global', description: 'Involve week suffer nearly. Again she list itself during chair require. Again result model wide. Media really their. Rule office word box parent loss.', created: '07/01/2021'},
  { work: 'Franco-Roberts', customer: 'Howard Fisher', seller: 'John Jacobson II', priority: 'Urgente', category: 'particular', description: 'Man explain stage floor. Impact quite purpose include daughter population. Bad thing action together never. Drop sort organization. Pattern reality him.', created: '08/01/2021'},
  { work: 'Gonzalez-Smith', customer: 'Lee PLC', seller: 'John Melendez', priority: 'Normal', category: 'cotação', description: 'Cover various ago consumer. Meeting successful recent certainly citizen. Stock attention hospital race animal score fill. Than type school really woman continue season. Rest now old court.', created: '09/01/2021'},
  { work: 'Long, Johnston and Vargas', customer: 'Lopez and Johnson', seller: 'Keith Schultz', priority: 'Alta', category: 'cotação', description: 'Professional although fish smile behavior. End short public myself speech. Than door strategy sport parent smile.', created: '10/01/2021'},
  { work: 'Martinez Building', customer: 'Martinez Group', seller: 'Kenneth Gallegos', priority: 'Baixa', category: 'concorrência', description: 'American particularly can party herself available. Carry hundred research visit suddenly condition road begin. Bag them increase similar other fly indicate. Attention lawyer bar.', created: '11/01/2021'},
  { work: 'Nicholson Ltd', customer: 'Mcbride-Owen', seller: 'Krystal Ramirez', priority: 'Normal', category: 'concorrência', description: 'Culture discussion wind interest. Pattern bill main must. Painting community bag remain. Trial get when certainly. Environment improve change project which cell. Media continue history woman.', created: '12/01/2021'},
  { work: 'Ortiz-Foster', customer: 'One Stop Building', seller: 'Mark Dudley', priority: 'Normal', category: 'global', description: 'Agent father authority between. Doctor far red whose. Early turn data bad protect mean most. Why according month hold number.', created: '13/01/2021'},
  { work: 'Prince-Callahan', customer: 'Reyes-Pope', seller: 'Michael Lang', priority: 'Alta', category: 'orçamento', description: 'Available citizen expect employee same structure skin. Last stand free produce type month major. Ability mean law audience. Grow result meet field themselves involve.', created: '14/01/2021'},
  { work: 'Riley Ltd', customer: 'Simple Trade', seller: 'Nathaniel Simpson', priority: 'Alta', category: 'consulta', description: 'Catch environment that pay race. Ago half no someone. Level picture model language film. Attention science involve police tonight idea appear.', created: '15/01/2021'},
  { work: 'Smith Group', customer: 'Sparks and Griffith', seller: 'Ryan Wells', priority: 'Normal', category: 'cotação', description: 'Green their yeah fall whom sea boy. Run hour personal top. Billion crime audience according hand.', created: '16/01/2021'},
  { work: 'Smith, Wilkinson and Brandt', customer: 'Stevens and Quinn', seller: 'Sean Mercer', priority: 'Normal', category: 'particular', description: 'Statement relate such rather market church young future. Now choose certain game say each. Eat care must member language think.', created: '17/01/2021'},
  { work: 'Smith-Brown', customer: 'Stone Fisher', seller: 'Sean Reed', priority: 'Baixa', category: 'particular', description: 'Control its network rich. Political about subject will simply throw task member. Theory behavior option realize. Six yet organization girl set door current. Ten forget drop science two.', created: '18/01/2021'},
]

export default entrysData
