const worksData = [
    {
    work: 'Barker Group',
    customer: 'Brown and Glass',
    address: 'Praia de Viana, 53',
    district: 'Caiçara - Adelaide', 
    city: 'Duarte do Oeste',
    uf: 'TO',
    zipcode: '36152-329',
    person: 'Shelly Beasley',
  },
  {
    work: 'Chan, Larsen and Lee',
    customer: 'Carter LLC',
    address: 'Vila Mariane Alves, 83',
    district: 'Alípio De Melo', 
    city: 'Nogueira',
    uf: 'AP',
    zipcode: '91015474',
    person: 'Michelle Thomas',
  },
  {
    work: 'Chen and Sons',
    customer: 'Chan-Jones',
    address: 'Passarela de Nunes, 222',
    district: 'Vila São Gabriel Jacui', 
    city: 'Cardoso',
    uf: 'PR',
    zipcode: '84198121',
    person: 'Tammy Collins',
  },
  {
    work: 'Collins, Stuart and Hodges',
    customer: 'Coleman-Schneider',
    address: 'Condomínio Novaes, 27',
    district: 'Vila Aeroporto Jaraguá', 
    city: 'Cardoso Verde',
    uf: 'PB',
    zipcode: '45213-985',
    person: 'Robert Thompson',
  },
  {
    work: 'Davis and Sons',
    customer: 'Gutierrez-Joseph',
    address: 'Viaduto da Costa, 908',
    district: 'Milionario', 
    city: 'Cunha',
    uf: 'PI',
    zipcode: '61961-118',
    person: 'Lori Ramirez',
  },
  {
    work: 'Douglas Building',
    customer: 'Holland Inc',
    address: 'Rodovia Ana Júlia da Rosa, 99',
    district: 'Caiçara - Adelaide', 
    city: 'da Rosa das Pedras',
    uf: 'DF',
    zipcode: '01686-870',
    person: 'Heather Wilson',
  },
  {
    work: 'Ellis, Hunt and Dean',
    customer: 'Holloway and Flynn',
    address: 'Via Sophia Barbosa, 3',
    district: 'Nova Cachoeirinha', 
    city: 'Sales dos Dourados',
    uf: 'RJ',
    zipcode: '01845-900',
    person: 'Edwin Acosta',
  },
  {
    work: 'Franco-Roberts',
    customer: 'Howard Fisher',
    address: 'Lago de Pires, 43',
    district: 'Vila Antena', 
    city: 'da Cruz',
    uf: 'CE',
    zipcode: '17671-159',
    person: 'Adam Williams',
  },
  {
    work: 'Gonzalez-Smith',
    customer: 'Lee PLC',
    address: 'Núcleo Correia, 1',
    district: 'Vila Jardim Alvorada', 
    city: 'da Mata de da Rocha',
    uf: 'MT',
    zipcode: '45421-513',
    person: 'Derek Allen',
  },
  {
    work: 'Long, Johnston and Vargas',
    customer: 'Lopez and Johnson',
    address: 'Lagoa Pietra Moraes, 5',
    district: 'Oeste', 
    city: 'Rezende da Prata',
    uf: 'BA',
    zipcode: '23119-901',
    person: 'William Casey',
  },
  {
    work: 'Martinez Building',
    customer: 'Martinez Group',
    address: 'Rodovia Rafaela Gonçalves, 21',
    district: 'Camponesa 1ª Seção', 
    city: 'das Neves',
    uf: 'AC',
    zipcode: '58748-673',
    person: 'Theresa Bradford',
  },
  {
    work: 'Nicholson Ltd',
    customer: 'Mcbride-Owen',
    address: 'Campo de da Rocha, 22',
    district: 'São Bernardo', 
    city: 'Pires de Minas',
    uf: 'PR',
    zipcode: '00934-224',
    person: 'Juan Silva',
  },
  {
    work: 'Ortiz-Foster',
    customer: 'One Stop Building',
    address: 'Alameda Rezende, 99',
    district: 'Santa Helena', 
    city: 'Gonçalves',
    uf: 'MG',
    zipcode: '35470841',
    person: 'Jessica Jordan',
  },
  {
    work: 'Prince-Callahan',
    customer: 'Reyes-Pope',
    address: 'Área Carvalho, 51',
    district: 'Céu Azul', 
    city: 'da Mata',
    uf: 'RS',
    zipcode: '74975-752',
    person: 'Christopher Silva',
  },
  {
    work: 'Riley Ltd',
    customer: 'Simple Trade',
    address: 'Distrito Nunes, 83',
    district: 'Grota', 
    city: 'Fernandes',
    uf: 'AC',
    zipcode: '48407-781',
    person: 'Carol Clark',
  },
  {
    work: 'Smith Group',
    customer: 'Sparks and Griffith',
    address: 'Passarela de Souza, 2',
    district: 'Confisco', 
    city: 'Cruz',
    uf: 'MG',
    zipcode: '36232035 da',
    person: 'Cassie Jenkins',
  },
  {
    work: 'Smith, Wilkinson and Brandt',
    customer: 'Stevens and Quinn',
    address: 'Jardim Azevedo, 89',
    district: 'Vila Aeroporto Jaraguá', 
    city: 'Lopes',
    uf: 'SP',
    zipcode: '31090-237',
    person: 'Mrs. Karen Holt',
  },
  {
    work: 'Smith-Brown',
    customer: 'Stone Fisher',
    address: 'Trevo de Viana, 19',
    district: 'Estrela', 
    city: 'Alves',
    uf: 'MA',
    zipcode: '26637-685',
    person: 'Kathleen Reyes',
  },
  {
    work: 'White, Garcia and Duncan',
    customer: 'Stone Ltda',
    address: 'Passarela Souza, 36',
    district: 'Aarão Reis', 
    city: 'Cardoso',
    uf: 'SC',
    zipcode: '42557521',
    person: 'Martha Parrish',
  },
  {
    work: 'Wood House',
    customer: 'Thompson SA',
    address: 'Sítio Oliveira, 8',
    district: 'Rio Branco', 
    city: 'de da Conceição',
    uf: 'MG',
    zipcode: '27259251 Carvalho',
    person: 'Ashley Smith',
  },
]

export default worksData
